### ISSUE TITLE
Android User interface

### ISSUE THREAD

**Issue by peterhansler2-byte** [rdoeffinger/Dictionary#177]
Android's navigation bar at the bottom hides the app's buttons to clear search and toggle languages.

**Comment by sandhya3191** [comment]
Hi @peterhansler2-byte, 

I'd like to look into fixing it, but could you please provide a bit more detail so I can understand it better?

- Which device or screen size are you using?
- Are the clear search and toggle language buttons located near the bottom of the screen?
- Is the issue that the Android system navigation bar (with back/home/recent buttons) is covering these app buttons?

A screenshot or layout explanation would be really helpful. Thanks in advance!

**Comment by rdoeffinger** [comment]
Thanks everyone but this should already be fixed by the 5.7.8 release along with several similar issues.
Re-open or open new ticket if not.
But yes, it is generally useful to report Phone and Android version, I had no problem to reproduce in this case but I think it only happens from Android 14 or 15 on.

**Comment by peterhansler2-byte** [comment]
Thanks for your reply.
This is a galaxy a53 phone.
Screenshot attached. Please notice nearly hidden app buttons at the bottom
of the screen. These stay the same even when page is scrolled.
Peter

**Comment by cweiske** [comment]
I still see this in QuickDic 5.8.2 (ID 131) from F-Droid.
The content is hidden behind the bottom navigation bar in the word list and on the help page.
On the word list, the last entry is not readable.
On the help page, the last line is not readable.

This is on LineageOS 23.2 (Android 16) on a Fairphone 4.

<details>
<summary>Screenshots</summary>
<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/5250440e-5d60-43bf-acbc-2119c8f081f3" />
<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/ac99cbcc-f852-4bab-9a2c-0e14b01174c4" />
</details>

**Comment by rdoeffinger** [comment]
There is an issue with the black bar in the top area, but otherwise the behaviour you see is exactly the way apps are supposed to behave on Android these days, with the list showing half-transparent under the navigation bar.
I believe you can set the navigation bar to not be transparent, then no content will be shown under it.

**Comment by cweiske** [comment]
The app has to make sure that it adds the relevant paddings to prevent getting disturbed by the system bars: https://developer.android.com/develop/ui/compose/system/insets

> [WindowInsets](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/WindowInsets) provides information about the system UI to ensure that your app draws in the correct area and your UI isn't obscured by the system UI.
> Displaying content behind the system UI is called going edge-to-edge. On this page, you learn about the different types of insets, how to go edge-to-edge, and how to use the inset APIs to animate your UI and ensure your app's content isn't obscured by system UI elements.

This is something that QuickDic has to do, and probably doesn't yet.

**Comment by rdoeffinger** [comment]
That is not the problem, these updates have been done, and as said, drawing under the transparent navigation bar is the whole point of this feature/inset handling.
However I did fix some issues in the latest release, notably that it was not possible to scroll up enough for the last item to emerge from under the navigation bar - in case that is what you meant (re-reading your comment, it probably was and I just did not read carefully enough, sorry).

**Comment by cweiske** [comment]
With 1.8.4, the issue is fixed in the translation list and the dictionary list. The fixing commit was probably 606b1e8f2fadf980b5e1032ce29fcf72b6f50a2a.

The problem persists on the help screen.

**Comment by rdoeffinger** [comment]
Hm, the web view does not support edge-to-edge unless the web page is specially adjusted. So just disabled it there, hope that fixes also that in latest release.

**Comment by cweiske** [comment]
Related commit: fe550399ff422bdc0e5d857227b6b131d5efec10
